### ISSUE TITLE
Opacity on particular labels.

### ISSUE THREAD

**Issue by gowachin** [ArneMeier/timeline#2]
Hi ! 

First, many thanks for your work !
I would like to specifiy opacity for some labels of my timeline. 
I tried to add arguments to the entrytemplate but can't manage to do it without breaking everything. 

Do you think it's possible ?

My opinion is that it could be possible by adding a optionnal argument to a generic entry, but since you need to have different commands for flip or shift entry, I guess it is difficult to have only a single entrytemplate with a lot of options ?

I'll try to fork your repo and work on this if you are okay with it !

Gowachin

**Comment by ArneMeier** [comment]
Hi, I do not how I have missed that, but will consider this in the next days. Sorry about that.

**Comment by gowachin** [comment]
Hi, no problem, I've been working on other stuff since. 
I also have been learning tikz a lot and may have found a creative solution to this issue. I need to test this a bit more but I hope I can complete py pull request around next week. 

I think I'll continue the discussion within the pull-request if this is okay for you ;)

**Comment by ArneMeier** [comment]
Thanks again for implementing these things. I like them. Regarding your other note about captions: you can embed the timeline into a figure environment which has captions. No need to reinvent the wheel.
